Algoritmo "Atividade07"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2026
Var
// Seção de Declarações das variáveis 
n, limite, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o número que quer fazer a tabuada: ")
leia(n)
escreva("Digite até que número quer que a tabuada vá: ")
leia(limite)

para i de 1 ate limite faça
     escreval(n," X",i ," =", n*i)
     
fimpara



Fimalgoritmo