'Algoritmo "Atividade11"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
n:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a nota aqui para ver se foi aprovado: ")
leia(n)

se (n >= 7) entao
   escreva("Foi aprovado")
senao
     escreva("Reprovado")
fimse

Fimalgoritmo