Algoritmo "Atividade02"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
n1: inteiro
n2: inteiro
soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite o primeiro número da soma: ")
leia(n1)
escreva("Digite o segundo: ")
leia(n2)
soma <- (n1 + n2)
escreva("A soma dos números é:", soma)

Fimalgoritmo