Algoritmo "ATIVIDADE21"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para n de 1 ate 50 faca
 escreval(n)
fimpara

Fimalgoritmo