Algoritmo "ATIVIDADE23"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
media, n1, n2, n3, n4, n5:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o número 1: ")
leia(n1)
escreva("Digite o número 2: ")
leia(n2)
escreva("Digite o número 3: ")
leia(n3)
escreva("Digite o número 4: ")
leia(n4)
escreva("Digite o número 5: ")
leia(n5)

media <- (n1+n2+n3+n4+n5)/5

escreva("A média dos números combinados é de: ",media)

Fimalgoritmo