Algoritmo "Atividade07"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num:inteiro
resp:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número para saber o resto da sua divisão por 2: ")
leia(num)
resp <- num mod 2
escreva("O resto da divisão de ",num," por 2 é de: ",resp)

Fimalgoritmo