Algoritmo "Atividade15"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um valor para saber se esta no intervalo entre 10 e 50: ")
leia(num)

se (num > 10)e (num < 50) entao
   escreva("Ele esta no intervalo certo.")
senao
     escreva("Não faz parte desse intervalo")
fimse



Fimalgoritmo