Algoritmo "Atividade16"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
l1:real
l2:real
l3:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Vamos ver se o triangulo é real... Diga o tamanho dos 3 lados: ")

leia(l1)
leia(l2)
leia(l3)

se (l1+l2 > l3) entao
   escreva("O triangulo é real")
senao
     escreva("O triangulo não é real")
fimse


Fimalgoritmo