Algoritmo "ATIVIDADE22"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
n:inteiro
soma:inteiro
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o número: ")
leia(n)

para i de 1 ate n faca
     soma <- soma + i

fimpara
escreva("A soma dos número em sequencia de ",n ," é de: ",soma)

Fimalgoritmo