Algoritmo "Atividade13"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Teste se esse número é positivo, negativo ou zero: ")
leia(num)

se (num = 0) entao
   escreva("O número é zero.")
senao
     se (num < 0) entao
        escreva("O número é negativo.")
     senao
          escreva("o número é positivo.")
     fimse
fimse

Fimalgoritmo