Algoritmo "Atividade04"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
base:inteiro
altura:inteiro
R:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual a altura: ")
leia(altura)
escreval("Qual a base: ")
leia(base)
R <- (base * altura)
escreval("O resultado da área é de:", r, " Unidade²")

Fimalgoritmo