Algoritmo "Atividade06"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
nota1:real
nota2:real
nota3:real
media:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite as 3 notas para calcular a média:")
escreva("Nota1: ")
leia(nota1)
escreva("Nota2: ")
leia(nota2)
escreva("Nota3: ")
leia(nota3)
media <- (nota1 + nota2 + nota3)/3

escreval("A média final ficou em: ", media)



Fimalgoritmo