Algoritmo "ATIVADE19"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
ano:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite o ano para saber se é bissexto: ")
leia(ano)

se (ano % 4 = 0)entao
   escreva("O ano é bissexto.")
senao
     escreva("O ano não é bissexto.")
fimse

Fimalgoritmo