Algoritmo "Atividade08"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
n1:real
n2:real
resp:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite os valores que vão se tornar exponentes: o primeiro é a base e o segundo a potência")
leia(n1)
leia(n2)
resp <- n1 ^ n2
Escreval("O resultado é de: ", resp)

Fimalgoritmo