Algoritmo "Atividade09"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
num:inteiro
resto:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva o número e descubra se é par ou impar: ")
leia(num)
resto <- num mod 2
se (resto = 0)entao
   escreva("O número é par.")
senao
   escreva("O número é impar.")
   
fimse


Fimalgoritmo